#!/bin/bash
# For terms and provenance see the LICENSE file at the top of this repository.
#
# Usage:
#
#   ( ./buildconf && ./configure && make && make check ) >& o.make.out
#
: nothing needs doing right now
exit 0
