#!/bin/sh

cd ${0%/*}/../..
set -o pipefail
declare -i ecode=0
for test in $@; do
    declare log=${test%.test}.log
    declare state=${test%.test}.state
    (
        if $test >& ${log?}; then
            status=PASS
            ecode=0
        else
            status=FAIL
            ecode=1
        fi
        echo "$status: $test"
        exit $ecode
    ) 2>&1 | tee $state
    if ((0 != $?)); then
        ecode=1
    fi
done
exit $ecode
