#!/bin/bash
: ${with_worktrees:=/build/worktrees}
: ${with_nearby:=/build/scold}

with_nearby=${with_nearby?} \
with_hypogeal_twilight=${with_hypogeal_twilight:-${with_worktrees?}/hypogeal-twilight/v0.LATEST} \
with_module_rigging=${with_module_rigging:-${with_worktrees?}/rigging/v1.LATEST} \
\
exec ${0%/*}/nearby
