# This is a -*- Makefile -*- of course
#
# It fulfills the requirements of function __directory_is_sufficiently_full_of_something_of_value()
# within HGTW_WITH_AMBIENT_COMPONENT_AND_EXPLICIT_PROBING_CANDIDATES_LIST
# It is trivial.
#
default:
