#!/bin/bash -p
# Copyright Yahoo Inc, 2021.
# Licensed under the terms of the Apache-2.0 license.
# For terms, see the LICENSE file at https://github.com/yahoo/tunitas-temerarious-flagship/blob/master/LICENSE
# For terms, see the LICENSE file at https://git.tunitas.technology/all/build/temerarious-flagship/tree/LICENSE
: ${with_build:=/build}
: ${with_worktrees:=${with_build?}/worktrees}

with_hypogeal_twilight=${with_hypogeal_twilight:-${with_worktrees?}/hypogeal-twilight/v0.LATEST} \
with_module_langu=${with_module_langu:-${with_worktrees?}/langu/v0.LATEST} \
with_module_rigging=${with_module_rigging:-${with_worktrees?}/rigging/v1.LATEST} \
\
exec ${0%/*}/nearby
