#!/bin/sh
cd ${0%/*}/.. || exit 70
: ${with_std_scold:=/opt/scold}
: ${with_std_tunitas:=/opt/tunitas}
: ${with_temerarious_flagship:=${PWD%/*/*}}
if [[ set == ${with_nearby:+set} ]]; then
    : ${with_hypogeal_twilight=${with_nearby?}/hypogeal-twilight}
else
    : ${with_hypogeal_twilight=${with_std_scold?}}
fi
eval \
    ${with_temerarious_flagship:+with_temerarious_flagship=$with_temerarious_flagship} \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    FORCE=1 \
    ./buildconf &&
./configure \
    ${with_std_scold:+--with-std-scold=$with_std_scold} \
    ${with_std_tunitas:+--with-std-tunitas=$with_std_tunitas} \
    ${with_temerarious_flagship:+--with-temerarious-flagship=$with_temerarious_flagship} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${end} &&
make &&
make check &&
echo OK DONE
