#!/bin/sh
#
# Called From:
#
#   a command line, for debugging, from any directory at all
#   e.g. ... you know ...
#
#   from Makefile.am within 'make check' via the macrotization 'check_driver_stanza'
#   e.g.
#     $(eval $(call check_driver_stanza, tests/ac, $(AC_TESTS)))
#   
# Usage
#
#    ...from any directory at all...
#    .../driver HGTW_WITH_USR_LOCAL ...etc...
#

cd ${0%/*}/../..
set -o pipefail
declare -i ecode=0
for test in $@; do
    declare log=${test%.test}.log
    declare state=${test%.test}.state
    (
        if $test >& ${log?}; then
            status=PASS
            ecode=0
        else
            status=FAIL
            ecode=1
        fi
        echo "$status: $test"
        exit $ecode
    ) 2>&1 | tee $state
    if ((0 != $?)); then
        ecode=1
    fi
done
exit $ecode
