# this is -*- sh -*- but should be sourced from the nearby */run.test definitions in the directories below
# Copyright Yahoo Inc. 2021.
# Licensed under the terms of the Apache-2.0 license.
# See the LICENSE file in https://github.com/yahoo/temerarious-flagship/blob/master/LICENSE for terms.
# See the LICENSE file at the top of this repository.
#
# Duties:
#
#   set -e, because this is a test driver (framework)
#   variables: default value for with_hyppogeal_twilight, with_temerarious_flagship
#   function: copy in a suitable boilerplate buildconf (we are not testing buildconf)
#   function: create a suitable boilerplate Makefrag.am
#
# Espectations:
#
#   configure.ac is being tested
#   ... it does not contain much except that which must be tested
#
set -e
# PWD is expected to be .../tests/ac/SOMETHING
function guess_hypogeal_twilight() {
    # prefer the development copy if you have it available, else find a nearby copy
    for guess in  /build/scold/hypogeal-twilight/ac {/exp/{scold,local},/opt/scold,usr/local}/share/hypogeal-twilight/ac ; do
        if [[ -d $guess ]] ; then
            guess=${guess%*/ac}
            guess=${guess%*/share/hypogeal-twilight}
            echo $guess
            return 0
        fi
    done
    echo /opt/scold
}
: ${prefix:=/exp/tunitas}
: ${with_hypogeal_twilight:=$(guess_hypogeal_twilight)} # use the standard install
: ${with_temerarious_flagship:=${PWD%/*/*/*}}
function prepare_buildconf() {
    # We're not testing buildconf, so use a "standard" one.   Any buildconf "that works" will do.
    # Make it work.
    if [[ ! -e ./buildconf ]] ; then
        if ! cp ../../../bc/template.autotools-buildconf buildconf ; then
            echo "${0}: error, could not copy a reasonable buildconf"
            exit 1
        fi 1>&2
    fi
    if [[ ! -x ./buildconf ]] ; then
        if ! chmod a+x ./buildconf ; then
            echo "${0}: error, could not make the buildconf executable"
            exit 1
        fi 1>&2
    fi
}
function prepare_Makefile_am() {
    function catty() {
        declare mode=$1; shift
        declare file=$1 ; shift
        declare tfile="$(dirname $file)/t99.$$.${RANDOM}.${file##*/}~"
        cat > ${tfile?} && chmod ${mode?} ${tfile?} && mv ${tfile?} ${file?}
    }
    catty a-x Makefile.am <<__Makefile__
# An minimal automake -*- Makefile -*-
# automatically generated by $0 at $(date --rfc-3339=seconds)
default:
__Makefile__
}
