#!/bin/bash
# For terms and provenance see the LICENSE file at the top of this repository.
cd ${0%/*}/.. || exit 70
: ${prefix:=/exp/scold}
: ${with_std_scold:=/opt/scold}
export PATH="$PATH:${prefix?}/bin:${with_std_scold?}/bin"
: ${with_nonstd_half:=/opt/nonstd/half}
: ${with_nearby:=/build/scold}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_incendiary_sophist:=${with_nearby?}/incendiary-sophist}
: ${with_module_half:=${with_nearby?}/module-half}
: ${with_module_nonstd:=${with_nearby?}/module-nonstd}
: ${with_module_posix:=${with_nearby?}/module-posix}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
: ${with_module_std:=${with_nearby?}/module-std}
: ${with_module_sys:=${with_nearby?}/module-sys}
if [[ -d ${with_nearby?}/module-string ]] && ! [[ -d ${with_nearby?}/module-c-string ]] ; then
    : ${with_module_string:=${with_nearby?}/module-string}
elif [[ -d ${with_nearby?}/module-c-string ]] ; then
    : ${with_module_string:=${with_nearby?}/module-c-string}
else
    : ${with_module_string:=${with_nearby?}/module-string}
fi
eval \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ./buildconf &&
./configure \
    ${prefix:+--prefix=$prefix} \
    ${with_std_scold:+--with-std-scold=$with_std_scold} \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_nonstd_half:+--with-nonstd-half=$with_nonstd_half} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_incendiary_sophist:+--with-incendiary-sophist=$with_incendiary_sophist} \
    ${with_module_half:+--with-module-half=$with_module_half} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_std:+--with-module-std=$with_module_std} \
    ${with_module_string:+--with-module-string=$with_module_string} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    ${end} && 
make &&
make check &&
echo OK DONE
